"""Project-specific exceptions."""

from enum import StrEnum


class DataPreparationError(Exception):
    """Base exception for expected data-preparation failures."""


class ConfigurationError(DataPreparationError):
    """Raised when a configuration file is invalid."""


class ChecksumMismatchError(DataPreparationError):
    """Raised when content does not match its pinned checksum."""


class UnsafeArchiveError(DataPreparationError):
    """Raised when an archive member cannot be extracted safely."""


class ManifestIntegrityError(DataPreparationError):
    """Raised when split metadata or generated manifests are inconsistent."""


class PreprocessingFailureCode(StrEnum):
    """Stable codes for an image that cannot enter a v0.1 method."""

    IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
    IMAGE_READ_FAILED = "IMAGE_READ_FAILED"
    IMAGE_DECODE_FAILED = "IMAGE_DECODE_FAILED"
    INVALID_DECODED_IMAGE = "INVALID_DECODED_IMAGE"
    IMAGE_RESIZE_FAILED = "IMAGE_RESIZE_FAILED"
    INVALID_PREPROCESSED_IMAGE = "INVALID_PREPROCESSED_IMAGE"


class ImagePreprocessingError(Exception):
    """Carry a stable failure code without converting a failure into a score."""

    def __init__(self, code: PreprocessingFailureCode, message: str) -> None:
        super().__init__(message)
        self.code = code


class ECCRegistrationFailureCode(StrEnum):
    """Stable failure codes for the v0.1 ECC registration primitive."""

    ECC_OPTIMIZATION_FAILED = "ECC_OPTIMIZATION_FAILED"
    ECC_RESULT_INVALID = "ECC_RESULT_INVALID"
    ECC_RESULT_NONFINITE = "ECC_RESULT_NONFINITE"
    ECC_ROTATION_LIMIT_EXCEEDED = "ECC_ROTATION_LIMIT_EXCEEDED"
    ECC_TRANSLATION_LIMIT_EXCEEDED = "ECC_TRANSLATION_LIMIT_EXCEEDED"
    ECC_WARP_FAILED = "ECC_WARP_FAILED"
    ECC_VALID_AREA_TOO_SMALL = "ECC_VALID_AREA_TOO_SMALL"


class ECCTemplateFailureCode(StrEnum):
    """Stable method-level failure codes for ECC normal-template fitting."""

    FIT_REFERENCE_COUNT_INVALID = "FIT_REFERENCE_COUNT_INVALID"
    FIT_REFERENCE_SET_INVALID = "FIT_REFERENCE_SET_INVALID"
    FIT_ANCHOR_PREPROCESSING_FAILED = "FIT_ANCHOR_PREPROCESSING_FAILED"
    FIT_INSUFFICIENT_REFERENCES = "FIT_INSUFFICIENT_REFERENCES"
    FIT_SUPPORT_EROSION_FAILED = "FIT_SUPPORT_EROSION_FAILED"
    FIT_SUPPORT_TOO_SMALL = "FIT_SUPPORT_TOO_SMALL"
    FIT_TEMPLATE_INVALID = "FIT_TEMPLATE_INVALID"


class ECCResidualFailureCode(StrEnum):
    """Stable image-level failure codes for ECC residual scoring."""

    SCORE_MASK_EROSION_FAILED = "SCORE_MASK_EROSION_FAILED"
    SCORE_EFFECTIVE_SUPPORT_TOO_SMALL = "SCORE_EFFECTIVE_SUPPORT_TOO_SMALL"
    SCORE_RESIDUAL_FILTER_FAILED = "SCORE_RESIDUAL_FILTER_FAILED"
    SCORE_RESULT_INVALID = "SCORE_RESULT_INVALID"


class ECCResidualStateError(Exception):
    """Reject scoring when no valid fitted ECC method state is available."""


class HOGFeatureFailureCode(StrEnum):
    """Stable failure codes for patch-grid and HOG extraction."""

    HOG_GRID_INVALID = "HOG_GRID_INVALID"
    HOG_EXTRACTION_FAILED = "HOG_EXTRACTION_FAILED"
    HOG_DESCRIPTOR_INVALID = "HOG_DESCRIPTOR_INVALID"


class HOGScalerFailureCode(StrEnum):
    """Stable method-level failure codes for position-wise scaler fitting."""

    HOG_FIT_REFERENCE_COUNT_INVALID = "HOG_FIT_REFERENCE_COUNT_INVALID"
    HOG_FIT_REFERENCE_SET_INVALID = "HOG_FIT_REFERENCE_SET_INVALID"
    HOG_FIT_REFERENCE_FEATURES_INVALID = "HOG_FIT_REFERENCE_FEATURES_INVALID"
    HOG_FIT_SCALER_FAILED = "HOG_FIT_SCALER_FAILED"
    HOG_FIT_SCALER_STATE_INVALID = "HOG_FIT_SCALER_STATE_INVALID"


class HOGModelFailureCode(StrEnum):
    """Stable method-level failure codes for position-wise SVM fitting."""

    HOG_MODEL_REFERENCE_COUNT_INVALID = "HOG_MODEL_REFERENCE_COUNT_INVALID"
    HOG_MODEL_REFERENCE_SET_INVALID = "HOG_MODEL_REFERENCE_SET_INVALID"
    HOG_MODEL_REFERENCE_FEATURES_INVALID = "HOG_MODEL_REFERENCE_FEATURES_INVALID"
    HOG_MODEL_SCALER_STATE_INVALID = "HOG_MODEL_SCALER_STATE_INVALID"
    HOG_MODEL_TRANSFORM_FAILED = "HOG_MODEL_TRANSFORM_FAILED"
    HOG_MODEL_TRANSFORM_INVALID = "HOG_MODEL_TRANSFORM_INVALID"
    HOG_MODEL_FIT_FAILED = "HOG_MODEL_FIT_FAILED"
    HOG_MODEL_STATE_INVALID = "HOG_MODEL_STATE_INVALID"


class HOGScoringFailureCode(StrEnum):
    """Stable image-level failure codes for Patch HOG scoring."""

    HOG_SCORE_FEATURE_RESULT_INVALID = "HOG_SCORE_FEATURE_RESULT_INVALID"
    HOG_SCORE_TRANSFORM_FAILED = "HOG_SCORE_TRANSFORM_FAILED"
    HOG_SCORE_TRANSFORM_INVALID = "HOG_SCORE_TRANSFORM_INVALID"
    HOG_SCORE_DECISION_FAILED = "HOG_SCORE_DECISION_FAILED"
    HOG_SCORE_PATCH_INVALID = "HOG_SCORE_PATCH_INVALID"
    HOG_SCORE_AGGREGATION_INVALID = "HOG_SCORE_AGGREGATION_INVALID"


class HOGScoringStateError(Exception):
    """Reject scoring when no valid fitted Patch HOG state is available."""


class DINOv2ScoringFailureCode(StrEnum):
    """Stable failure codes for the fixed v0.2 DINOv2 scoring path."""

    DINO_RESOLUTION_INVALID = "DINO_RESOLUTION_INVALID"
    DINO_IMAGE_TYPE_INVALID = "DINO_IMAGE_TYPE_INVALID"
    DINO_IMAGE_SHAPE_INVALID = "DINO_IMAGE_SHAPE_INVALID"
    DINO_IMAGE_DTYPE_INVALID = "DINO_IMAGE_DTYPE_INVALID"
    DINO_IMAGE_CONTIGUITY_INVALID = "DINO_IMAGE_CONTIGUITY_INVALID"
    DINO_TORCH_UNAVAILABLE = "DINO_TORCH_UNAVAILABLE"
    DINO_MODEL_STATE_INVALID = "DINO_MODEL_STATE_INVALID"
    DINO_PREPROCESSING_FAILED = "DINO_PREPROCESSING_FAILED"
    DINO_PREPROCESSING_RESULT_INVALID = "DINO_PREPROCESSING_RESULT_INVALID"
    DINO_FEATURE_EXTRACTION_FAILED = "DINO_FEATURE_EXTRACTION_FAILED"
    DINO_FEATURE_RESULT_INVALID = "DINO_FEATURE_RESULT_INVALID"
    DINO_REFERENCE_COUNT_INVALID = "DINO_REFERENCE_COUNT_INVALID"
    DINO_MEMORY_BANK_INVALID = "DINO_MEMORY_BANK_INVALID"
    DINO_DISTANCE_COMPUTATION_FAILED = "DINO_DISTANCE_COMPUTATION_FAILED"
    DINO_DISTANCE_RESULT_INVALID = "DINO_DISTANCE_RESULT_INVALID"
    DINO_SCORE_INVALID = "DINO_SCORE_INVALID"


class DINOv2ScoringError(Exception):
    """Carry a stable failure code for a rejected v0.2 scoring operation."""

    def __init__(self, code: DINOv2ScoringFailureCode, message: str) -> None:
        super().__init__(message)
        self.code = code


class ThresholdCalibrationFailureCode(StrEnum):
    """Stable failure codes for normal-only threshold calibration."""

    CALIBRATION_METHOD_INVALID = "CALIBRATION_METHOD_INVALID"
    CALIBRATION_EMPTY = "CALIBRATION_EMPTY"
    CALIBRATION_PATH_INVALID = "CALIBRATION_PATH_INVALID"
    CALIBRATION_SCORE_TYPE_MISMATCH = "CALIBRATION_SCORE_TYPE_MISMATCH"
    CALIBRATION_SCORE_RECORD_INVALID = "CALIBRATION_SCORE_RECORD_INVALID"
    CALIBRATION_RESULT_INVALID = "CALIBRATION_RESULT_INVALID"


class ThresholdClassificationFailureCode(StrEnum):
    """Stable failure codes for fixed-threshold image classification."""

    CLASSIFICATION_PATH_INVALID = "CLASSIFICATION_PATH_INVALID"
    CLASSIFICATION_CALIBRATION_INVALID = "CLASSIFICATION_CALIBRATION_INVALID"
    CLASSIFICATION_SCORE_TYPE_MISMATCH = "CLASSIFICATION_SCORE_TYPE_MISMATCH"
    CLASSIFICATION_SCORE_RECORD_INVALID = "CLASSIFICATION_SCORE_RECORD_INVALID"
    CLASSIFICATION_RESULT_INVALID = "CLASSIFICATION_RESULT_INVALID"


class BatchClassificationFailureCode(StrEnum):
    """Stable failure codes for label-free batch classification."""

    BATCH_CLASSIFICATION_EMPTY = "BATCH_CLASSIFICATION_EMPTY"
    BATCH_CLASSIFICATION_PATH_INVALID = "BATCH_CLASSIFICATION_PATH_INVALID"
    BATCH_CLASSIFICATION_CALIBRATION_INVALID = "BATCH_CLASSIFICATION_CALIBRATION_INVALID"
    BATCH_CLASSIFICATION_ITEM_FAILED = "BATCH_CLASSIFICATION_ITEM_FAILED"
    BATCH_CLASSIFICATION_RESULT_INVALID = "BATCH_CLASSIFICATION_RESULT_INVALID"


class LabelRevealFailureCode(StrEnum):
    """Stable failure codes for the final-test label reveal boundary."""

    LABEL_REVEAL_BATCH_INVALID = "LABEL_REVEAL_BATCH_INVALID"
    LABEL_REVEAL_LABELS_EMPTY = "LABEL_REVEAL_LABELS_EMPTY"
    LABEL_REVEAL_LABEL_RECORD_INVALID = "LABEL_REVEAL_LABEL_RECORD_INVALID"
    LABEL_REVEAL_LABEL_DUPLICATE_PATH = "LABEL_REVEAL_LABEL_DUPLICATE_PATH"
    LABEL_REVEAL_PATH_MISSING = "LABEL_REVEAL_PATH_MISSING"
    LABEL_REVEAL_PATH_EXTRA = "LABEL_REVEAL_PATH_EXTRA"
    LABEL_REVEAL_ORDER_MISMATCH = "LABEL_REVEAL_ORDER_MISMATCH"


class ImageMetricsFailureCode(StrEnum):
    """Stable failure codes for image-level metric calculation."""

    METRICS_LABEL_REVEAL_INVALID = "METRICS_LABEL_REVEAL_INVALID"
    METRICS_CLASS_SUPPORT_INVALID = "METRICS_CLASS_SUPPORT_INVALID"
    METRICS_COMPUTATION_FAILED = "METRICS_COMPUTATION_FAILED"
    METRICS_RESULT_INVALID = "METRICS_RESULT_INVALID"


class CPULatencyFailureCode(StrEnum):
    """Stable failure codes for CPU latency measurement."""

    LATENCY_METHOD_INVALID = "LATENCY_METHOD_INVALID"
    LATENCY_INPUT_EMPTY = "LATENCY_INPUT_EMPTY"
    LATENCY_PATH_INVALID = "LATENCY_PATH_INVALID"
    LATENCY_SCORER_INVALID = "LATENCY_SCORER_INVALID"
    LATENCY_ENVIRONMENT_CAPTURE_FAILED = "LATENCY_ENVIRONMENT_CAPTURE_FAILED"
    LATENCY_SCORE_CALL_FAILED = "LATENCY_SCORE_CALL_FAILED"
    LATENCY_SCORE_RECORD_INVALID = "LATENCY_SCORE_RECORD_INVALID"
    LATENCY_TIMER_INVALID = "LATENCY_TIMER_INVALID"
    LATENCY_RESULT_INVALID = "LATENCY_RESULT_INVALID"


class FailureCaseSelectionFailureCode(StrEnum):
    """Stable failure codes for deterministic failure-case selection."""

    FAILURE_SELECTION_REVEAL_INVALID = "FAILURE_SELECTION_REVEAL_INVALID"
    FAILURE_SELECTION_RESULT_INVALID = "FAILURE_SELECTION_RESULT_INVALID"


class HardGateDecisionFailureCode(StrEnum):
    """Stable failure codes for the fixed hard-gate decision."""

    DECISION_METRICS_INVALID = "DECISION_METRICS_INVALID"
    DECISION_LATENCY_INVALID = "DECISION_LATENCY_INVALID"
    DECISION_METHOD_MISMATCH = "DECISION_METHOD_MISMATCH"
    DECISION_PROCESS_EVIDENCE_INVALID = "DECISION_PROCESS_EVIDENCE_INVALID"
    DECISION_RESULT_INVALID = "DECISION_RESULT_INVALID"


class EvaluationArtifactError(Exception):
    """Reject an invalid or non-immutable evaluation artifact bundle."""
